export const LOAD_VENUES_SUCCESS = "LOAD_VENUES_SUCCESS";
export  const LOAD_VENUES_ERROR = "LOAD_VENUES_ERROR";
export  const CREATE_VENUE_SUCCESS = "CREATE_VENUE_SUCCESS";
export const UPDATE_VENUE_SUCCESS = "UPDATE_VENUE_SUCCESS";
export const DELETE_VENUE_OPTIMISTIC = "DELETE_VENUE_OPTIMISTIC";
export const LOAD_CITIES_SUCCESS = "LOAD_CITIES_SUCCESS";
export const LOAD_VENUESP_SUCCESS = "LOAD_VENUESP_SUCCESS";
